"""Engine error hierarchy (spec §7.1)."""
from __future__ import annotations


class EngineError(Exception):
    def __init__(self, stage: str, message: str, cause: Exception | None = None):
        super().__init__(message)
        self.stage = stage
        self.cause = cause


class OCRError(EngineError): ...
class AgentOutputError(EngineError): ...
class ModelUnavailableError(EngineError): ...
class ToolExecutionError(EngineError): ...
class FormatterError(EngineError): ...
class InputValidationError(EngineError): ...
